# coding: utf-8

"""
    Clinic Reservations API

    A simple API for managing patient appointments and doctor schedules.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.admin_api import router as AdminApiRouter
from openapi_server.apis.appointment_api import router as AppointmentApiRouter
from openapi_server.apis.auth_api import router as AuthApiRouter
from openapi_server.apis.doctor_api import router as DoctorApiRouter
from openapi_server.apis.patient_api import router as PatientApiRouter

app = FastAPI(
    title="Clinic Reservations API",
    description="A simple API for managing patient appointments and doctor schedules.",
    version="1.0.0",
)

app.include_router(AdminApiRouter)
app.include_router(AppointmentApiRouter)
app.include_router(AuthApiRouter)
app.include_router(DoctorApiRouter)
app.include_router(PatientApiRouter)
